# Generated by Django 4.1.5 on 2023-01-22 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('btc_rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('net_assets', models.DecimalField(decimal_places=10, max_digits=20)),
                ('pnl', models.DecimalField(decimal_places=10, max_digits=20)),
                ('pnl_index', models.DecimalField(decimal_places=10, max_digits=20)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm.account')),
            ],
        ),
    ]
